// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomarsDocumentDataSlicesSlice =
  | SeparatorSlice
  | VideoSlice
  | UbicationSlice
  | LotsSlice
  | ImageSeparatorSlice
  | HousesSlice
  | GalerySlice
  | DiferentiatorsSlice
  | ContactSlice
  | ConceptSlice
  | AmenitiesSlice
  | NavigationSlice
  | HeaderSlice;

/**
 * Content for Homars documents
 */
interface HomarsDocumentData {
  /**
   * Slice Zone field in *Homars*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homars.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomarsDocumentDataSlicesSlice> /**
   * Meta Title field in *Homars*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homars.meta_title
   * - **Tab**: SEO & Metadata Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homars*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homars.meta_description
   * - **Tab**: SEO & Metadata Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homars*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homars.meta_image
   * - **Tab**: SEO & Metadata Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homars document from Prismic
 *
 * - **API ID**: `homars`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomarsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomarsDocumentData>, "homars", Lang>;

export type AllDocumentTypes = HomarsDocument;

/**
 * Item in *Amenities → Default → Primary → GroupAmenities*
 */
export interface AmenitiesSliceDefaultPrimaryGroupamenitiesItem {
  /**
   * Label field in *Amenities → Default → Primary → GroupAmenities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.groupamenities[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Icon field in *Amenities → Default → Primary → GroupAmenities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.groupamenities[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Amenities → Default → Primary*
 */
export interface AmenitiesSliceDefaultPrimary {
  /**
   * Tittle field in *Amenities → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * GroupAmenities field in *Amenities → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.groupamenities[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupamenities: prismic.GroupField<
    Simplify<AmenitiesSliceDefaultPrimaryGroupamenitiesItem>
  >;

  /**
   * Subtittle field in *Amenities → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * ImageAmenitie field in *Amenities → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.imageamenitie
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageamenitie: prismic.ImageField<never>;

  /**
   * LinkButton field in *Amenities → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Amenities → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: amenities.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;
}

/**
 * Default variation for Amenities Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AmenitiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AmenitiesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Amenities*
 */
type AmenitiesSliceVariation = AmenitiesSliceDefault;

/**
 * Amenities Shared Slice
 *
 * - **API ID**: `amenities`
 * - **Description**: Amenities
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AmenitiesSlice = prismic.SharedSlice<
  "amenities",
  AmenitiesSliceVariation
>;

/**
 * Primary content in *Concept → Default → Primary*
 */
export interface ConceptSliceDefaultPrimary {
  /**
   * Tittle field in *Concept → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: concept.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Subtittle field in *Concept → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: concept.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * Description field in *Concept → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: concept.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Description2 field in *Concept → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: concept.default.primary.description2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description2: prismic.KeyTextField;

  /**
   * LinkButton field in *Concept → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: concept.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Concept → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: concept.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;

  /**
   * ImageConcept field in *Concept → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: concept.default.primary.imageconcept
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageconcept: prismic.ImageField<never>;
}

/**
 * Default variation for Concept Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConceptSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConceptSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Concept*
 */
type ConceptSliceVariation = ConceptSliceDefault;

/**
 * Concept Shared Slice
 *
 * - **API ID**: `concept`
 * - **Description**: Concept
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConceptSlice = prismic.SharedSlice<
  "concept",
  ConceptSliceVariation
>;

/**
 * Item in *Contact → Default → Primary → GroupContact*
 */
export interface ContactSliceDefaultPrimaryGroupcontactItem {
  /**
   * Subtittle field in *Contact → Default → Primary → GroupContact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.groupcontact[].subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary → GroupContact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.groupcontact[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → GroupSocialMedia*
 */
export interface ContactSliceDefaultPrimaryGroupsocialmediaItem {
  /**
   * Icon field in *Contact → Default → Primary → GroupSocialMedia*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.groupsocialmedia[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * LinkIcon field in *Contact → Default → Primary → GroupSocialMedia*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.groupsocialmedia[].linkicon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkicon: prismic.LinkField;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Tittle field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * GroupContact field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.groupcontact[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupcontact: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryGroupcontactItem>
  >;

  /**
   * SocialMedia field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.socialmedia
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialmedia: prismic.KeyTextField;

  /**
   * GroupSocialMedia field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.groupsocialmedia[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupsocialmedia: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryGroupsocialmediaItem>
  >;

  /**
   * LinkPrivacy field in *Contact → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.linkprivacy
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkprivacy: prismic.LinkField;

  /**
   * Privacy field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.privacy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  privacy: prismic.KeyTextField;

  /**
   * Logo field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Diferentiators → Default → Primary → GroupDifferentiators*
 */
export interface DiferentiatorsSliceDefaultPrimaryGroupdifferentiatorsItem {
  /**
   * TextIcon field in *Diferentiators → Default → Primary → GroupDifferentiators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: diferentiators.default.primary.groupdifferentiators[].texticon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texticon: prismic.KeyTextField;

  /**
   * Icon field in *Diferentiators → Default → Primary → GroupDifferentiators*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: diferentiators.default.primary.groupdifferentiators[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Diferentiators → Default → Primary*
 */
export interface DiferentiatorsSliceDefaultPrimary {
  /**
   * Tittle field in *Diferentiators → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: diferentiators.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * GroupDifferentiators field in *Diferentiators → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: diferentiators.default.primary.groupdifferentiators[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupdifferentiators: prismic.GroupField<
    Simplify<DiferentiatorsSliceDefaultPrimaryGroupdifferentiatorsItem>
  >;

  /**
   * LinkButton field in *Diferentiators → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: diferentiators.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Diferentiators → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: diferentiators.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;
}

/**
 * Default variation for Diferentiators Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiferentiatorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DiferentiatorsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Diferentiators*
 */
type DiferentiatorsSliceVariation = DiferentiatorsSliceDefault;

/**
 * Diferentiators Shared Slice
 *
 * - **API ID**: `diferentiators`
 * - **Description**: Diferentiators
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiferentiatorsSlice = prismic.SharedSlice<
  "diferentiators",
  DiferentiatorsSliceVariation
>;

/**
 * Item in *Galery → Default → Primary → GroupGalery*
 */
export interface GalerySliceDefaultPrimaryGroupgaleryItem {
  /**
   * Date field in *Galery → Default → Primary → GroupGalery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galery.default.primary.groupgalery[].date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Image1 field in *Galery → Default → Primary → GroupGalery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galery.default.primary.groupgalery[].image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * Image2 field in *Galery → Default → Primary → GroupGalery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galery.default.primary.groupgalery[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image3 field in *Galery → Default → Primary → GroupGalery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galery.default.primary.groupgalery[].image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Primary content in *Galery → Default → Primary*
 */
export interface GalerySliceDefaultPrimary {
  /**
   * Tittle field in *Galery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galery.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * GroupGalery field in *Galery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: galery.default.primary.groupgalery[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupgalery: prismic.GroupField<
    Simplify<GalerySliceDefaultPrimaryGroupgaleryItem>
  >;
}

/**
 * Default variation for Galery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Galery*
 */
type GalerySliceVariation = GalerySliceDefault;

/**
 * Galery Shared Slice
 *
 * - **API ID**: `galery`
 * - **Description**: Galery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalerySlice = prismic.SharedSlice<"galery", GalerySliceVariation>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Tittle field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Subtittle field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * Description field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * LinkLogo field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linklogo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklogo: prismic.LinkField;

  /**
   * Logo field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * LinkMoreInfo field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkmoreinfo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkmoreinfo: prismic.LinkField;

  /**
   * LabelMoreInfo field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.labelmoreinfo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelmoreinfo: prismic.KeyTextField;

  /**
   * LinkScheduleCall field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkschedulecall
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkschedulecall: prismic.LinkField;

  /**
   * LabelScheduleCall field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.labelschedulecall
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelschedulecall: prismic.KeyTextField;

  /**
   * LinkWhatsApp field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkwhatsapp
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkwhatsapp: prismic.LinkField;

  /**
   * IconWhatsApp field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.iconwhatsapp
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  iconwhatsapp: prismic.ImageField<never>;

  /**
   * BackgroundImage field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.backgroundimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundimage: prismic.ImageField<never>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Item in *Houses → Default → Primary → GroupButtons*
 */
export interface HousesSliceDefaultPrimaryGroupbuttonsItem {
  /**
   * ActiveButton field in *Houses → Default → Primary → GroupButtons*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: houses.default.primary.groupbuttons[].activebutton
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  activebutton: prismic.BooleanField;

  /**
   * LabelButton field in *Houses → Default → Primary → GroupButtons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupbuttons[].labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;

  /**
   * Image1 field in *Houses → Default → Primary → GroupButtons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupbuttons[].image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * Image2 field in *Houses → Default → Primary → GroupButtons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupbuttons[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image3 field in *Houses → Default → Primary → GroupButtons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupbuttons[].image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Item in *Houses → Default → Primary → GroupFirstSection*
 */
export interface HousesSliceDefaultPrimaryGroupfirstsectionItem {
  /**
   * Label1 field in *Houses → Default → Primary → GroupFirstSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupfirstsection[].label1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label1: prismic.KeyTextField;

  /**
   * Label2 field in *Houses → Default → Primary → GroupFirstSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupfirstsection[].label2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label2: prismic.KeyTextField;
}

/**
 * Item in *Houses → Default → Primary → GroupFirstFloor*
 */
export interface HousesSliceDefaultPrimaryGroupfirstfloorItem {
  /**
   * Label field in *Houses → Default → Primary → GroupFirstFloor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupfirstfloor[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Houses → Default → Primary → GroupSecondFloor*
 */
export interface HousesSliceDefaultPrimaryGroupsecondfloorItem {
  /**
   * Label field in *Houses → Default → Primary → GroupSecondFloor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupsecondfloor[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Houses → Default → Primary → GroupThirdFloor*
 */
export interface HousesSliceDefaultPrimaryGroupthirdfloorItem {
  /**
   * Label field in *Houses → Default → Primary → GroupThirdFloor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupthirdfloor[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Houses → Default → Primary*
 */
export interface HousesSliceDefaultPrimary {
  /**
   * Tittle field in *Houses → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Subtittle field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * GroupButtons field in *Houses → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupbuttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupbuttons: prismic.GroupField<
    Simplify<HousesSliceDefaultPrimaryGroupbuttonsItem>
  >;

  /**
   * GroupFirstSection field in *Houses → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupfirstsection[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupfirstsection: prismic.GroupField<
    Simplify<HousesSliceDefaultPrimaryGroupfirstsectionItem>
  >;

  /**
   * FirstFloor field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.firstfloor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  firstfloor: prismic.KeyTextField;

  /**
   * GroupFirstFloor field in *Houses → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupfirstfloor[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupfirstfloor: prismic.GroupField<
    Simplify<HousesSliceDefaultPrimaryGroupfirstfloorItem>
  >;

  /**
   * SecondFloor field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.secondfloor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondfloor: prismic.KeyTextField;

  /**
   * GroupSecondFloor field in *Houses → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupsecondfloor[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupsecondfloor: prismic.GroupField<
    Simplify<HousesSliceDefaultPrimaryGroupsecondfloorItem>
  >;

  /**
   * ThirdFloor field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.thirdfloor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  thirdfloor: prismic.KeyTextField;

  /**
   * GroupThirdFloor field in *Houses → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.groupthirdfloor[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupthirdfloor: prismic.GroupField<
    Simplify<HousesSliceDefaultPrimaryGroupthirdfloorItem>
  >;

  /**
   * PriceText field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.pricetext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pricetext: prismic.KeyTextField;

  /**
   * PriceNumber field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.pricenumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pricenumber: prismic.KeyTextField;

  /**
   * PriceDescription field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.pricedescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pricedescription: prismic.KeyTextField;

  /**
   * LinkButton field in *Houses → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Houses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: houses.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;
}

/**
 * Default variation for Houses Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HousesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HousesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Houses*
 */
type HousesSliceVariation = HousesSliceDefault;

/**
 * Houses Shared Slice
 *
 * - **API ID**: `houses`
 * - **Description**: Houses
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HousesSlice = prismic.SharedSlice<"houses", HousesSliceVariation>;

/**
 * Primary content in *ImageSeparator → Default → Primary*
 */
export interface ImageSeparatorSliceDefaultPrimary {
  /**
   * Image field in *ImageSeparator → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_separator.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageSeparator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSeparatorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSeparatorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSeparator*
 */
type ImageSeparatorSliceVariation = ImageSeparatorSliceDefault;

/**
 * ImageSeparator Shared Slice
 *
 * - **API ID**: `image_separator`
 * - **Description**: ImageSeparator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSeparatorSlice = prismic.SharedSlice<
  "image_separator",
  ImageSeparatorSliceVariation
>;

/**
 * Item in *Lots → Default → Primary → GroupLots*
 */
export interface LotsSliceDefaultPrimaryGrouplotsItem {
  /**
   * Subtittle field in *Lots → Default → Primary → GroupLots*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.grouplots[].subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * Description field in *Lots → Default → Primary → GroupLots*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.grouplots[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * LinkButton field in *Lots → Default → Primary → GroupLots*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.grouplots[].linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Lots → Default → Primary → GroupLots*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.grouplots[].labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;
}

/**
 * Primary content in *Lots → Default → Primary*
 */
export interface LotsSliceDefaultPrimary {
  /**
   * Tittle field in *Lots → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Description field in *Lots → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Description2 field in *Lots → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.description2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description2: prismic.KeyTextField;

  /**
   * GroupLots field in *Lots → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.grouplots[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplots: prismic.GroupField<Simplify<LotsSliceDefaultPrimaryGrouplotsItem>>;

  /**
   * LinkButton field in *Lots → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Lots → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;

  /**
   * ImageLots field in *Lots → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lots.default.primary.imagelots
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagelots: prismic.ImageField<never>;
}

/**
 * Default variation for Lots Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LotsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LotsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Lots*
 */
type LotsSliceVariation = LotsSliceDefault;

/**
 * Lots Shared Slice
 *
 * - **API ID**: `lots`
 * - **Description**: Lots
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LotsSlice = prismic.SharedSlice<"lots", LotsSliceVariation>;

/**
 * Item in *Navigation → Default → Primary → GroupSection*
 */
export interface NavigationSliceDefaultPrimaryGroupsectionItem {
  /**
   * LinkLabel field in *Navigation → Default → Primary → GroupSection*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.groupsection[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *Navigation → Default → Primary → GroupSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.groupsection[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * LinkLogo field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.linklogo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklogo: prismic.LinkField;

  /**
   * ImageLogo field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.imagelogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagelogo: prismic.ImageField<never>;

  /**
   * GroupSection field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.groupsection[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupsection: prismic.GroupField<
    Simplify<NavigationSliceDefaultPrimaryGroupsectionItem>
  >;

  /**
   * LinkButton field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *Separator → Default → Primary*
 */
export interface SeparatorSliceDefaultPrimary {
  /**
   * ImageSeparator field in *Separator → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: separator.default.primary.imageseparator
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageseparator: prismic.ImageField<never>;
}

/**
 * Default variation for Separator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeparatorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeparatorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Separator*
 */
type SeparatorSliceVariation = SeparatorSliceDefault;

/**
 * Separator Shared Slice
 *
 * - **API ID**: `separator`
 * - **Description**: Separator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeparatorSlice = prismic.SharedSlice<
  "separator",
  SeparatorSliceVariation
>;

/**
 * Item in *Ubication → Default → Primary → GroupListOne*
 */
export interface UbicationSliceDefaultPrimaryGrouplistoneItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupListOne*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistone[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Ubication → Default → Primary → GroupListTwo*
 */
export interface UbicationSliceDefaultPrimaryGrouplisttwoItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupListTwo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplisttwo[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Ubication → Default → Primary → GroupListThree*
 */
export interface UbicationSliceDefaultPrimaryGrouplistthreeItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupListThree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistthree[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Ubication → Default → Primary → GroupListFour*
 */
export interface UbicationSliceDefaultPrimaryGrouplistfourItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupListFour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistfour[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Ubication → Default → Primary → GroupListFive*
 */
export interface UbicationSliceDefaultPrimaryGrouplistfiveItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupListFive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistfive[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Ubication → Default → Primary → GroupListSix*
 */
export interface UbicationSliceDefaultPrimaryGrouplistsixItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupListSix*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistsix[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Ubication → Default → Primary → GroupListSeven*
 */
export interface UbicationSliceDefaultPrimaryGrouplistsevenItem {
  /**
   * Label field in *Ubication → Default → Primary → GroupListSeven*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistseven[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Ubication → Default → Primary*
 */
export interface UbicationSliceDefaultPrimary {
  /**
   * Tittle field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.tittle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tittle: prismic.RichTextField;

  /**
   * Subtittle field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.subtittle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtittle: prismic.KeyTextField;

  /**
   * ListOne field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.listone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listone: prismic.KeyTextField;

  /**
   * GroupListOne field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplistone: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGrouplistoneItem>
  >;

  /**
   * ListTwo field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.listtwo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listtwo: prismic.KeyTextField;

  /**
   * GroupListTwo field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplisttwo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplisttwo: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGrouplisttwoItem>
  >;

  /**
   * ListThree field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.listthree
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listthree: prismic.KeyTextField;

  /**
   * GroupListThree field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistthree[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplistthree: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGrouplistthreeItem>
  >;

  /**
   * ListFour field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.listfour
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listfour: prismic.KeyTextField;

  /**
   * GroupListFour field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistfour[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplistfour: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGrouplistfourItem>
  >;

  /**
   * ListFive field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.listfive
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listfive: prismic.KeyTextField;

  /**
   * GroupListFive field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistfive[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplistfive: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGrouplistfiveItem>
  >;

  /**
   * ListSix field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.listsix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listsix: prismic.KeyTextField;

  /**
   * GroupListSix field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistsix[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplistsix: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGrouplistsixItem>
  >;

  /**
   * ListSeven field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.listseven
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listseven: prismic.KeyTextField;

  /**
   * GroupListSeven field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.grouplistseven[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grouplistseven: prismic.GroupField<
    Simplify<UbicationSliceDefaultPrimaryGrouplistsevenItem>
  >;

  /**
   * LinkButton field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.linkbutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton: prismic.LinkField;

  /**
   * LabelButton field in *Ubication → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ubication.default.primary.labelbutton
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelbutton: prismic.KeyTextField;
}

/**
 * Default variation for Ubication Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UbicationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UbicationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ubication*
 */
type UbicationSliceVariation = UbicationSliceDefault;

/**
 * Ubication Shared Slice
 *
 * - **API ID**: `ubication`
 * - **Description**: Ubication
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UbicationSlice = prismic.SharedSlice<
  "ubication",
  UbicationSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Video field in *Video → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video: prismic.ImageField<never>;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomarsDocument,
      HomarsDocumentData,
      HomarsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AmenitiesSlice,
      AmenitiesSliceDefaultPrimaryGroupamenitiesItem,
      AmenitiesSliceDefaultPrimary,
      AmenitiesSliceVariation,
      AmenitiesSliceDefault,
      ConceptSlice,
      ConceptSliceDefaultPrimary,
      ConceptSliceVariation,
      ConceptSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimaryGroupcontactItem,
      ContactSliceDefaultPrimaryGroupsocialmediaItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      DiferentiatorsSlice,
      DiferentiatorsSliceDefaultPrimaryGroupdifferentiatorsItem,
      DiferentiatorsSliceDefaultPrimary,
      DiferentiatorsSliceVariation,
      DiferentiatorsSliceDefault,
      GalerySlice,
      GalerySliceDefaultPrimaryGroupgaleryItem,
      GalerySliceDefaultPrimary,
      GalerySliceVariation,
      GalerySliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HousesSlice,
      HousesSliceDefaultPrimaryGroupbuttonsItem,
      HousesSliceDefaultPrimaryGroupfirstsectionItem,
      HousesSliceDefaultPrimaryGroupfirstfloorItem,
      HousesSliceDefaultPrimaryGroupsecondfloorItem,
      HousesSliceDefaultPrimaryGroupthirdfloorItem,
      HousesSliceDefaultPrimary,
      HousesSliceVariation,
      HousesSliceDefault,
      ImageSeparatorSlice,
      ImageSeparatorSliceDefaultPrimary,
      ImageSeparatorSliceVariation,
      ImageSeparatorSliceDefault,
      LotsSlice,
      LotsSliceDefaultPrimaryGrouplotsItem,
      LotsSliceDefaultPrimary,
      LotsSliceVariation,
      LotsSliceDefault,
      NavigationSlice,
      NavigationSliceDefaultPrimaryGroupsectionItem,
      NavigationSliceDefaultPrimary,
      NavigationSliceVariation,
      NavigationSliceDefault,
      SeparatorSlice,
      SeparatorSliceDefaultPrimary,
      SeparatorSliceVariation,
      SeparatorSliceDefault,
      UbicationSlice,
      UbicationSliceDefaultPrimaryGrouplistoneItem,
      UbicationSliceDefaultPrimaryGrouplisttwoItem,
      UbicationSliceDefaultPrimaryGrouplistthreeItem,
      UbicationSliceDefaultPrimaryGrouplistfourItem,
      UbicationSliceDefaultPrimaryGrouplistfiveItem,
      UbicationSliceDefaultPrimaryGrouplistsixItem,
      UbicationSliceDefaultPrimaryGrouplistsevenItem,
      UbicationSliceDefaultPrimary,
      UbicationSliceVariation,
      UbicationSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
